### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by davidbIQ** [flux-web/flux-web#12]
Hi there, 
I get the following error after running the installation instructions on a fresh install in 2 different clusters, the second being a simple minikube env.

E0918 09:41:16.936194   29480 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod b80c34335429adf50d600404d65fe663735215b636a8d8d5730d13e32be1ae51, uid : exit status 1: 2019/09/18 15:41:16 socat[34482] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused

This was from doing:
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=flux-web,app.kubernetes.io/instance=flux-web" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

but changing the default namespace to the flux namespace where the installation instructions directed the install to go.  It just generated the podname for flux-web in the flux ns.

Would love some additional direction.  In both of these places flux is installed in it's own namespace (not flux or default).

**Comment by idobry** [comment]
Hi @davidbIQ,
Flux-web must be at the same ns where flux is.
So, if you deployed flux in ns xxx then you should  `helm install . --namespace xxx....`

**Comment by davidbIQ** [comment]
I found I also needed to update the values file accordingly to point to our flux install, and add the ingress points, then it worked well :).  Thanks 👍
