### ISSUE TITLE
Account for tag filter when showing available versions

### ISSUE THREAD

**Issue by adusumillipraveen** [flux-web/flux-web#22]
We set a tag filter in flux for prod-*
But if I view the UI here I see tags i'm not interested in:

![63155090-da3a4000-c009-11e9-88b7-9ba77bbe7a93](https://user-images.githubusercontent.com/47391951/67097872-f5186480-f1b2-11e9-891d-126355044d6a.png)

Moving from archived project https://github.com/idobry/flux-web/issues/4

**Comment by idobry** [comment]
Please don't use this archived version for flux-web, we no longer support it.

**Comment by adusumillipraveen** [comment]
Sorry, I was meant to update with latest image. 

<img width="1280" alt="Screenshot 2019-10-18 at 22 01 03" src="https://user-images.githubusercontent.com/47391951/67128225-f1a4cd80-f1f2-11e9-8e83-e4126fbc8817.png">
